name: create and upload linux images
on:
  release:
    types: [ published ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build-and-push-image-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get tag name
        run: echo "TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Build and push config-assessment-tool-backend Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: backend/Dockerfile
          push: true
          tags: |
            ghcr.io/appdynamics/config-assessment-tool-backend-linux:${{ env.TAG }}
            ghcr.io/appdynamics/config-assessment-tool-backend-linux:latest

      - name: Build and push config-assessment-tool-frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: frontend/Dockerfile
          push: true
          tags: |
            ghcr.io/appdynamics/config-assessment-tool-frontend-linux:${{ env.TAG }}
            ghcr.io/appdynamics/config-assessment-tool-frontend-linux:latest
